{
    "append_sys_path": true,
    "arch": "x86_64",
    "building": true,
    "caching": true,
    "created": 1705689730,
    "default_patch_lock": "no_lock",
    "failure_description": "The following package conflicts occurred: (arch-aarch64 <--!--> ~arch==x86_64)",
    "from_cache": false,
    "graph": "{'nodes': [((('fillcolor', '#F6F6F6'), ('fontsize', 10), ('style', 'filled,dashed')), [('_1', 'arch-aarch64'), ('_2', '~arch==x86_64')])], 'edges': [((('arrowsize', '1'), ('color', 'red'), ('fontcolor', 'red'), ('style', 'bold')), [('_1', '_2', 'CONFLICT')])]}",
    "host": "ryanz800",
    "implicit_packages": [
        "~platform==linux",
        "~arch==x86_64",
        "~os==Ubuntu-20.04"
    ],
    "load_time": 0.0,
    "num_loaded_packages": 0,
    "os": "Ubuntu-20.04",
    "package_caching": false,
    "package_filter": [],
    "package_orderers": null,
    "package_paths": [
        "/home/ryan/packages",
        "/home/ryan/.rez/packages/int",
        "/home/ryan/.rez/packages/ext"
    ],
    "package_requests": [
        "python",
        "platform-linux",
        "arch-aarch64",
        "os-Ubuntu-20.04"
    ],
    "parent_suite_path": null,
    "patch_locks": {},
    "platform": "linux",
    "requested_timestamp": null,
    "resolved_ephemerals": [],
    "resolved_packages": [],
    "rez_path": "/opt/rez/lib/python3.8/site-packages/rez",
    "rez_version": "2.114.1",
    "serialize_version": "4.7",
    "solve_time": 1.1682510375976562e-05,
    "status": "failed",
    "suite_context_name": null,
    "timestamp": 1705689730,
    "user": "ryan"
}